<?php /* Smarty version 2.6.7, created on 2011-09-12 04:23:29
         compiled from achievements/whatisMemeja.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/%%3F^3F3^3F3AF2A3%%whatisMemeja.tpl.html.inc'] = 'bdd2f54d4985a073ca67c659d51122c4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'achievements/whatisMemeja.tpl.html', 6, false),)), $this); ?>
<?php
function _smarty_tplfunc_bdd2f54d4985a073ca67c659d51122c4_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'cms','mgr' => 'cms','choice' => 'show','code' => 'howtogetachievement'), $_smarty);
}



?>
