<?php /* Smarty version 2.6.7, created on 2011-09-11 01:35:52
         compiled from achievements/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/%%86^860^86063F6A%%home.tpl.html.inc'] = 'a09d9670af06e9106e4c981f0c493193';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'achievements/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a09d9670af06e9106e4c981f0c493193_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'achievements','mgr' => 'achievements'), $_smarty);
}



?>
