<?php /* Smarty version 2.6.7, created on 2011-09-10 12:55:38
         compiled from duels/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/%%F4^F48^F484B3A4%%home.tpl.html.inc'] = '6d5ea7fe39c7a4425cea4d2edbd70121';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'duels/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_6d5ea7fe39c7a4425cea4d2edbd70121_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'duels','mgr' => 'duels'), $_smarty);
}



?>
