<?php /* Smarty version 2.6.7, created on 2011-09-08 04:41:21
         compiled from caption/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/^%%2C^2C1^2C182F38%%home.tpl.html.inc'] = '11d13097194113b9a7b66064f281217d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'caption/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_11d13097194113b9a7b66064f281217d_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'caption','mgr' => 'caption'), $_smarty);
}



?>
