<?php /* Smarty version 2.6.7, created on 2011-09-12 14:57:59
         compiled from cms/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/^%%41^414^4149CF9E%%home.tpl.html.inc'] = '61b72aef7841ba52621a16b21fe9becd';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'cms/home.tpl.html', 3, false),)), $this); ?>
<?php
function _smarty_tplfunc_61b72aef7841ba52621a16b21fe9becd_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mgr' => 'cms','mod' => 'cms'), $_smarty);
}



?>
