<?php /* Smarty version 2.6.7, created on 2011-09-08 09:16:07
         compiled from admin/cms/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_admin_c//^%%30^30A^30A2AC7E%%home.tpl.html.inc'] = 'aa94ea2ef53433f0a6606f0bc0e5d443';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'admin/cms/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_aa94ea2ef53433f0a6606f0bc0e5d443_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mgr' => 'cms','mod' => 'cms'), $_smarty);
}



?>
