<?php /* Smarty version 2.6.7, created on 2011-09-08 09:14:01
         compiled from admin/meme/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_admin_c//^%%9A^9A0^9A0A037B%%home.tpl.html.inc'] = 'ab93af05475ef613cb76c2c6a1977d1d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'admin/meme/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ab93af05475ef613cb76c2c6a1977d1d_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'meme','mgr' => 'meme'), $_smarty);
}



?>
