<?php /* Smarty version 2.6.7, created on 2011-09-08 09:20:12
         compiled from admin/user/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_admin_c//^%%BF^BFE^BFEDD000%%home.tpl.html.inc'] = 'f1e53c3a4d2ef642d01dc23e362ca6ce';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'admin/user/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f1e53c3a4d2ef642d01dc23e362ca6ce_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'user','mgr' => 'user'), $_smarty);
}



?>
