<?php /* Smarty version 2.6.7, created on 2011-09-08 09:17:58
         compiled from admin/question/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_admin_c//^%%FB^FB8^FB8D56C8%%home.tpl.html.inc'] = '3221c6f119615b5fcd0ac88d49d09741';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'admin/question/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3221c6f119615b5fcd0ac88d49d09741_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'question','mgr' => 'question'), $_smarty);
}



?>
